baseURL = 'http://FoxTechWorld.github.io/'
languageCode = 'pt-br'
title = 'FoxTechWorld'
theme = 'binario'
paginate = '10'
googleAnalytics="G-T8PSN4T418"

[Author]
  name = "KitsuneSemCalda"
  bio = "KitsuneSemCalda é a identidade secreta de um estudante de ciencias de computação (ou talvez não)"

[Params]
  opengraph = true
  schema = true
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  columns = 2
  mainSections = ["posts"]
  colorTheme = "dark-green"
  authorbox = true
  comments = true
  related = true
  relatedMax = true

[Params.Entry]
  meta = ["date", "categories", "tags"]
  toc = true
  tocOpen = true

[Params.Social]
  github = "KitsuneSemCalda"
  linkedin = "arthur-augusto-magalhães-55761b220"

[permalinks]
  posts = "/:year/:month/:title/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      noNullishOperator = false
      precision = 0
    [minify.tdewolff.json]
      keepNumbers = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1
