baseURL = 'http://FoxTechWorld.github.io/'
languageCode = 'pt-br'
title = 'FoxTechWorld'
theme = 'binario'
paginate = '10'
googleAnalytics="G-T8PSN4T418"

[Author]
  name = "KitsuneSemCalda"

[permalinks]
  posts = "/:filename/"
