baseURL = 'http://FoxTechWorld.github.io/'
languageCode = 'pt-br'
title = 'FoxTechWorld'
theme = 'binario'
paginate = '10'
googleAnalytics="G-T8PSN4T418"

[Author]
  name = "KitsuneSemCalda"
  bio = "KitsuneSemCalda é a identidade secreta de um estudante de ciencias de computação (ou talvez não)"

[Params]
  opengraph = true
  schema = true
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  columns = 2
  mainSections = ["posts"]
  colorTheme = "dark-green"
  authorbox = true
  comments = true
  related = true
  relatedMax = true

[Params.Entry]
  meta = ["date", "categories", "tags"]
  toc = true
  tocOpen = true

[Params.Social]
  github = "KitsuneSemCalda"
  linkedin = "arthur-augusto-magalhães-55761b220"
